#!/bin/zsh

export PATH="$PATH:$(du "$HOME/.local/bin" | cut -f2 | paste -sd ':')"
export PATH="$PATH:$HOME/.local/share/gem/ruby/2.7.0/bin"
export GOPATH="$HOME/dev/go"
export PATH="$GOPATH/bin:$PATH"
export PATH="$HOME/.bin:$PATH"
export LANG="en_US.UTF-8"
export LC_COLLATE="C"
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="brave"
export READER="zathura"
export VISUAL="st -e nvim"
export PAGER="bat"
export MANPAGER="nvim -c 'set ft=man' -"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_DIR="$HOME/.local"
export XDG_CACHE_HOME="$HOME/.cache"
export GTK_THEME="yrwqs_phocus"
export LESSHISTFILE="-"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export XKB_DEFAULT_LAYOUT="hu"
