#!/bin/bash

# define dependencies
dependencies=(git feh picom slop termite xorg-server abook alsa-card-profiles alsa-lib alsa-plugins alsa-utils dunst emacs exa ffmpeg ffmpegthumbnailer fzf imagemagick lxappearance-gtk3 maim mpc mpd mpv mupdf ncmpcpp neomutt neovim newsboat nitrogen obconf openbox pamixer poppler pulseaudio pulseaudio-alsa pulsemixer qutebrowser ranger rofi scrot sxiv tint2 transmission-cli transmission-gtk ttf-nerd-fonts-symbols urlscan w3m xautolock xclip xdg-user-dirs xdg-utils xdotool xf86-input-libinput xf86-video-intel xmobar xmonad xmonad-contrib xorg-font-util xorg-fonts-misc xorg-mkfontscale xorg-xinit xorg-xrandr xorg-xsetroot xorg-server-common xorg-server-devel xorg-setxkbmap xorg-xclipboard xorg-xdpyinfo xorg-xev xorg-xfontsel xorg-xinput xorg-xmodmap xorg-xprop xorg-xrandr xorg-xrdb xorg-xset xorg-xsetroot xorg-xwininfo xscreensaver youtube-dl zathura zathura-pdf-poppler zsh)
dependencies_aur=(awesome-git brave-dev-bin ttf-material-design-icons-git urlview nerd-fonts-iosevka)

clear

echo "Updating repositories ..."
sudo pacman -Sy --noconfirm

install_dependencies() {
  sudo pacman -S --needed --noconfirm "$@"
}


echo "Installing dependencies ..."
sleep 2
install_dependencies "${dependencies[@]}"


read -p "Install dependencies from aur? [ Y / n ]" -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]
then
	if command -v pikaur &> /dev/null
	then
		echo "Installing packages from AUR ..."
	else
  		aur_tmp_dir=$(mktemp -d) && cd "$aur_tmp_dir" || exit 1
  		git clone "https://aur.archlinux.org/pikaur.git" "$aur_tmp_dir"
  		makepkg -sim --noconfirm
	fi
	pikaur -S --needed --noconfirm "${dependencies_aur[@]}"
fi

echo "Warning!"
echo "This will overwrite your configuration files!"
read -p "Copy dotfiles? [ Y / n ] " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]
then
	url="https://github.com/yrwq/dotfiles.git"
	temp_directory_dotfiles=$(mktemp -d)
  	git clone "$url" "$temp_directory_dotfiles"
  	cp -rb "$temp_directory_dotfiles"/. ~
	walls="https://github.com/yrwq/walls.git"
  	git clone "$walls" ~/.wp
fi
clear

# finalize
{
  sudo chsh -s /usr/bin/zsh "$USER"
}

clear
echo "Installation finished, restart your session."
