#!/bin/bash

#
# install - install my dotfiles
#

install_dependencies(){
    sh $PWD/pkgs
}

ask(){
    clear
    printf "\n"
    read -rp "${1} " ans
    case $ans in
        y*|Y*)
            $2
        ;;
    esac
}

copy_dots(){
    url="https://github.com/yrwq/dotfiles.git"
    temp_directory_dotfiles=$(mktemp -d)
    git clone "$url" "$temp_directory_dotfiles"
    yes | cp -rf "$temp_directory_dotfiles"/. ~
}

install_others(){
    # st
    cd ~/.local/src/st
    make && sudo make install
    # colorpicker
    git clone https://github.com/ym1234/colorpicker ~/.local/src/colorpcker
    cd ~/.local/src/colorpicker
    make && sudo make install
}

ask "Install dependencies?" install_dependencies
ask "Copy dotfiles?" copy_dots
ask "Install other requirements?" install_others
