#!/bin/sh

#
# pkgs - install dependencies for my dotfiles
#

arch_package_list() {
    printf '%s ' \
        "git" \
        "feh" \
        "slop" \
        "xorg-server" \
        "alsa-lib" \
        "alsa-plugins" \
        "alsa-utils" \
        "exa" \
        "ffmpeg" \
        "ffmpegthumbnailer" \
        "fzf" \
        "imagemagick" \
        "lxappearance" \
        "maim" \
        "mpc" \
        "mpd" \
        "mpv" \
        "ncmpcpp" \
        "neomutt" \
        "neovim" \
        "newsboat" \
        "pamixer" \
        "pulseaudio" \
        "pulseaudio-alsa" \
        "pulsemixer" \
        "ranger" \
        "rofi" \
        "scrot" \
        "transmission-cli" \
        "ttf-nerd-fonts-symbols" \
        "urlscan" \
        "w3m" \
        "xclip" \
        "xautolock" \
        "xdg-user-dirs" \
        "xdg-utils" \
        "xdotool" \
        "xf86-input-libinput" \
        "xf86-video-intel" \
        "xf86-video-amd" \
        "xorg-font-util" \
        "xorg-fonts-misc" \
        "xorg-mkfontscale" \
        "xorg-xinit" \
        "xorg-xsetroot" \
        "xorg-server-common" \
        "xorg-server-devel" \
        "xorg-setxkbmap" \
        "xorg-xclipboard" \
        "xorg-xev" \
        "xorg-xfontsel" \
        "xorg-xinput" \
        "xorg-xmodmap" \
        "xorg-xprop" \
        "xorg-xrandr" \
        "xorg-xrdb" \
        "xorg-xset" \
        "xorg-xwininfo" \
        "youtube-dl" \
        "zsh" \
        "unzip" \
        "unclutter" \
        "ueberzug" \
        "sxiv" \
        "man-db" \
        "libnotify" \
        "jq" \
        "rofimoji" \
        "highlight" \
        "inotify-tools" \
        "awesome-git" \
        "urlview" \
        "nerd-fonts-iosevka" \
        "vidir" \
        "lf-bin" \
        "picom-jonaburg-git" \
        "mutt-wizard-git" \
        "libxft-bgra" \
        "brave-bin"
}

install_arch_packages() {
    if command -v yay &> /dev/null
    then
        printf 'Installing packages for Arch Linux...\n'
    else
        echo "Installing Yay."
        aur_tmp_dir=$(mktemp -d) && cd "$aur_tmp_dir" || exit 1
        git clone "https://aur.archlinux.org/yay.git" "$aur_tmp_dir"
        makepkg -sim --noconfirm
    fi

    yay -Syu --needed "$(arch_package_list)"

    printf "Done.\n"
}

# Detect distro by package manager
if command -v pacman &> /dev/null
then
    distro="arch"
elif command -v apt &> /dev/null
then
    distro="deb"
else
    distro="idk"
fi

# Handle distro and install packages
case $distro in
    arch)
        install_arch_packages
        ;;
    deb)
        printf "Your distrobutions is not supported yet!\n"
        ;;
    idk)
        printf "Sorry, your distrobution is not supported by this script.\n"
        ;;
esac

