[DEFAULT]
;; Download directory
;; Where to download songs
download_dir = ~/etc/music

;; Ffmpeg
;; If True ffmpeg, will be used to convert the song to mp3,
;; add metadata and thumbnail
ffmpeg = True
