#!/bin/bash
set shell bash
set shellopts '-eu'
set ifs "\n"
set scrolloff 10
set period 1
set hiddenfiles ".*:*.aux:*.log:*.bbl:*.bcf:*.blg:*.run.xml"

# Vars that depend on environmental variables
$lf -remote "send $id set previewer ${XDG_CONFIG_HOME:-$HOME/.config}/lf/scope"

# cmds/functions
cmd open ${{
    case $(file --mime-type $f -b) in

        image/vnd.djvu|application/pdf|application/octet-stream) setsid -f zathura $fx >/dev/null 2>&1 ;;

        text/*) $EDITOR $fx;;

        image/x-xcf) setsid -f gimp $f >/dev/null 2>&1 ;;

        image/svg+xml) display -- $f ;;

        image/*) setsid -f sxiv $fx >/dev/null 2>&1 ;;

        audio/*) mpv --audio-display=no $f ;;

        video/*) setsid -f mpv $f -quiet >/dev/null 2>&1 ;;

        application/pdf|application/vnd*|application/epub*) setsid -f zathura $fx >/dev/null 2>&1 ;;

        *) $EDITOR $fx ;;

    esac
}}

cmd mkdir $mkdir -p "$(echo $* | tr ' ' '\ ')"

cmd delete ${{
    rm -rf -- $fx
}}

cmd moveto ${{
    clear; tput cup $(($(tput lines)/3)); tput bold
    set -f
    clear; echo "Move to where?"
    dest="$(cut -d'	' -f2- ${XDG_CONFIG_HOME:-$HOME/.config}/directories | fzf | sed 's|~|$HOME|' )" &&
    for x in $fx; do
        eval mv -iv \"$x\" \"$dest\"
    done &&
    notify-send " File(s) moved to $dest."
}}

cmd copyto ${{
    clear; tput cup $(($(tput lines)/3)); tput bold
    set -f
    clear; echo "Copy to where?"
    dest="$(cut -d'	' -f2- ${XDG_CONFIG_HOME:-$HOME/.config}/directories | fzf | sed 's|~|$HOME|' )" &&
    for x in $fx; do
        eval cp -ivr \"$x\" \"$dest\"
    done &&
    notify-send " File(s) copies to $dest."
}}

cmd on-cd &{{
    printf "\033]0; lf - $(pwd | sed "s|$HOME|~|")\007" > /dev/tty
}}
on-cd

cmd bulkrename $vidir

# Bindings
map e $st -e $EDITOR $f &
map gg top
map D delete
map C copyto
map M moveto
map <c-n> push :mkdir<space>
map <enter> shell

map B bulkrename
map bg $feh --bg-scale $f
map gp $push
