#!/bin/sh

# Use neovim for vim if present.
#[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

alias \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner" \
	slop="slop -o" \
	ls="exa --icons" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ka="killall" \
	g="gitui" \
	ga="git add" \
	gc="git commit -m" \
	gp="git push -u origin main" \
	mk="make && sudo make install" \
	f="$FILE" \
	v="$EDITOR" \
	z="zathura" \
	pik="pikaur --noconfirm" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
