#!/bin/sh

bf      ${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-files
bd      ${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs
cfz     $ZDOTDIR/.zshrc
cfu     ${XDG_CONFIG_HOME:-$HOME/.config}/newsboat/urls
cfl     ${XDG_CONFIG_HOME:-$HOME/.config}/lf/lfrc
cfr     ${XDG_CONFIG_HOME:-$HOME/.config}/river/init
cfa     ${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc
cfw     ${XDG_CONFIG_HOME:-$HOME/.config}/wezterm/wezterm.lua
cfh     ${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprland.conf
