#!/bin/sh

wlr-randr --output eDP-1 --scale 1.3


export XDG_SESSION_TYPE=wayland 
export XDG_SESSION_DESKTOP=river
export XDG_CURRENT_DESKTOP=river
export GDK_BACKEND=wayland
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export SDL_VIDEODRIVER=wayland 
export _JAVA_AWT_WM_NONREPARENTING=1
export WLR_NO_HARDWARE_CURSORS=1 
export MOZ_DISABLE_RDD_SANDBOX=1
export MOZ_ENABLE_WAYLAND=1 
export OZONE_PLATFORM=wayland

riverctl spawn "waybar -c ~/.config/waybar/config-simple.jsonc -s ~/.config/waybar/style-simple.css"
riverctl spawn "wp river.png"
riverctl spawn "fnott"
riverctl spawn "wl-clipboard"
riverctl spawn "emacs --daemon"
riverctl spawn "wl-paste --watch clapboard store"
riverctl spawn "wl-copy --watch clapboard store"
riverctl spawn "mpd"

mod="Mod4"
riverctl focus-follows-cursor normal

riverctl map normal $mod Return spawn "alacritty"
riverctl map normal $mod Space spawn "fuzzel"
riverctl map normal $mod R spawn "alacritty -e yazi"
riverctl map normal $mod N spawn "alacritty -e newsboat"
riverctl map normal $mod M spawn "alacritty -e music"
riverctl map normal $mod C spawn "alacritty -e weechat"
riverctl map normal $mod+Shift M spawn "alacritty -e neomutt"
riverctl map normal $mod T spawn "emacsclient -c"

riverctl map normal $mod+Shift F spawn "edit"
riverctl map normal $mod E spawn "neovide"
riverctl map normal Mod1 E spawn "zed"

riverctl map normal $mod d spawn "flow cycle-tags next"
riverctl map normal $mod a spawn "flow cycle-tags previous"

riverctl map normal $mod Q close
riverctl map normal $mod+Shift E exit

riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

riverctl map normal $mod+Shift Return zoom

riverctl map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"

riverctl map normal $mod+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivertile "main-count -1"

riverctl map normal $mod Up    send-layout-cmd rivertile "main-location top"
riverctl map normal $mod Right send-layout-cmd rivertile "main-location right"
riverctl map normal $mod Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal $mod Left  send-layout-cmd rivertile "main-location left"

riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view

for i in $(seq 1 9); do
    tagmask=$((1 << ($i - 1)))
    riverctl map normal $mod $i set-focused-tags $tagmask
    riverctl map normal $mod+Shift $i set-view-tags $tagmask
done

riverctl map normal $mod+Shift Space toggle-float
riverctl map normal $mod F toggle-fullscreen

riverctl map normal None F12 spawn "pamixer --toggle-mute"
riverctl map normal None F11 spawn "pamixer -i 5"
riverctl map normal None F10 spawn "pamixer -d 5"
riverctl map normal None F9 spawn "brightnessctl set +5%"
riverctl map normal None F8 spawn "brightnessctl set 5%-"

for mode in normal locked
do

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn "pamixer -i 5"
    riverctl map $mode None XF86AudioLowerVolume  spawn "pamixer -d 5"
    riverctl map $mode None XF86AudioMute         spawn "pamixer --toggle-mute"

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioPlay  spawn "mpc toggle"
    riverctl map $mode None XF86AudioPrev  spawn "mpc previous"
    riverctl map $mode None XF86AudioNext  spawn "mpc next"

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn "brightnessctl set +5%"
    riverctl map $mode None XF86MonBrightnessDown spawn "brightnessctl set 5%-"

    riverctl map $mode None XF86KbdBrightnessUp   spawn "kbd up"
    riverctl map $mode None XF86KbdBrightnessDown spawn "kbd down"
done

# Set repeat rate
riverctl set-repeat 50 300

# Set app-ids of views which should float
riverctl float-filter-add "float"
riverctl float-filter-add "popup"
riverctl float-filter-add "menu"
riverctl float-filter-add "swappy"
riverctl rule-add -title "menu" float

# Set app-ids of views which should use client side decorations
riverctl csd-filter-add "swappy"
riverctl csd-filter-add "Emacs"
riverctl csd-filter-add "emacs"

# Set opacity and fade effect
riverctl opacity 1.0 0.95 0.0 0.1 20

gnome_schema="org.gnome.desktop.interface"
gsettings set "$gnome_schema" gtk-theme "Rosepine-Light"
gsettings set "$gnome_schema" icon-theme "WhiteSur-light"
gsettings set "$gnome_schema" cursor-theme "phinger-cursors-light"
gsettings set "$gnome_schema" font-name "AzukiFont Nerd Font 10"
gsettings set "$gnome_schema" color-scheme prefer-light
gsettings set "$gnome_schema" gtk-decoration-layout ""

riverctl border-color-focused 0x575779
riverctl border-color-unfocused 0xfaf4ed
riverctl border-width 3

riverctl attach-mode bottom

riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &
