#!/bin/sh

# riverctl spawn 'waybar'

mod="Mod4"
riverctl focus-follows-cursor normal

riverctl map normal $mod Return spawn "foot"
riverctl map normal $mod S spawn wofi
riverctl map normal $mod Q close
riverctl map normal $mod+Shift E exit

riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

riverctl map normal $mod+Shift Return zoom

riverctl map normal $mod H mod-main-factor -0.05
riverctl map normal $mod L mod-main-factor +0.05

riverctl map normal $mod+Control K mod-main-count +1
riverctl map normal $mod+Control J mod-main-count -1

riverctl map normal $mod+Mod1 H move left 100
riverctl map normal $mod+Mod1 J move down 100
riverctl map normal $mod+Mod1 K move up 100
riverctl map normal $mod+Mod1 L move right 100

riverctl map normal $mod+Mod1+Shift H resize horizontal -100
riverctl map normal $mod+Mod1+Shift J resize vertical 100
riverctl map normal $mod+Mod1+Shift K resize vertical -100
riverctl map normal $mod+Mod1+Shift L resize horizontal 100

riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view

for i in $(seq 1 9); do
    tagmask=$((1 << ($i - 1)))
    riverctl map normal $mod $i set-focused-tags $tagmask
    riverctl map normal $mod+Shift $i set-view-tags $tagmask
done

riverctl map normal $mod+Shift Space toggle-float
riverctl map normal $mod F toggle-fullscreen

# Mod+{Up,Right,Down,Left} to change master orientation
riverctl map normal $mod Down layout rivertile top
riverctl map normal $mod Left layout rivertile right
riverctl map normal $mod Up layout rivertile down
riverctl map normal $mod Right layout rivertile left

# Set repeat rate
riverctl set-repeat 50 300

# Set app-ids of views which should float
riverctl float-filter-add "float"
riverctl float-filter-add "popup"

# Set app-ids of views which should use client side decorations
riverctl csd-filter-add "swappy"
riverctl float-filter-add "swappy"
# riverctl csd-filter-add "firefox"

# Set opacity and fade effect
riverctl opacity 1.0 0.95 0.0 0.1 20

riverctl border-color-focused '#a9b665'
riverctl border-color-unfocused '#212121'
riverctl border-width 3

riverctl attach-mode bottom
riverctl layout rivertile left
