#!/bin/sh

riverctl spawn "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway"
riverctl spawn "/usr/libexec/xdg-desktop-portal-wlr"
riverctl spawn "/usr/libexec/xdg-desktop-portal -r"
riverctl spawn "wl-paste --type text --watch cliphist store"
riverctl spawn "wl-paste --type image --watch cliphist store"
riverctl spawn "waybar-launch &"
riverctl spawn "kanshi"
riverctl spawn "dunst"
riverctl spawn "swaybg -i ~/etc/dl/8.png"

riverctl spawn "gsettings set org.gnome.desktop.interface gtk-theme 'phocus'"
riverctl spawn "gsettings set org.gnome.desktop.interface font-name 'Ioskeley Mono 10'"
riverctl spawn "gsettings set org.gnome.desktop.interface icon-theme 'WhiteSur'"
riverctl spawn "gsettings set org.gnome.desktop.interface cursor-theme 'phinger-cursors-light'"
riverctl spawn "gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'"

riverctl keyboard-layout hu

riverctl map normal Super Return spawn foot
riverctl map normal Super Space spawn fuzzel
riverctl map normal Super r spawn "foot -e yazi"
riverctl map normal Super t spawn "foot -e nvim todo.md"
riverctl map normal Super a spawn "flow cycle-tags previous"
riverctl map normal Super d spawn "flow cycle-tags next"
riverctl map normal Super Q close
riverctl map normal Super+Shift E exit
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous
riverctl map normal Super+Shift Return zoom

riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

riverctl map normal Control+Shift+Alt H move left 100
riverctl map normal Control+Shift+Alt J move down 100
riverctl map normal Control+Shift+Alt K move up 100
riverctl map normal Control+Shift+Alt L move right 100

riverctl map normal Super+Control+Alt+Shift H resize horizontal -100
riverctl map normal Super+Control+Alt+Shift J resize vertical 100
riverctl map normal Super+Control+Alt+Shift K resize vertical -100
riverctl map normal Super+Control+Alt+Shift L resize horizontal 100

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

riverctl map normal Super+Shift Space toggle-float
riverctl map normal Super F toggle-fullscreen

riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

riverctl declare-mode passthrough
riverctl map normal Super F11 enter-mode passthrough
riverctl map passthrough Super F11 enter-mode normal

for mode in normal locked
do
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
    riverctl map $mode None XF86KbdBrightnessUp spawn "kbd i"
    riverctl map $mode None XF86KbdBrightnessDown spawn "kbd d"
done

riverctl background-color 0x1d2021
riverctl border-color-unfocused 0x282828
riverctl border-color-focused 0x665c54

riverctl set-repeat 40 300

riverctl xcursor-theme "phinger-cursors-light" "24"

riverctl rule-add -app-id 'float*' -title 'foo' float

riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &
