#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# Wallpaper early for slightly less ugly startup
hsetroot -fill ~/.wp/city.png &
xrdb ~/.Xresources &

Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-e quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close_and_remove

hc keybind $Mod-Return or , and . compare tags.focus.frame_count = 1 . compare tags.focus.curframe_wcount = 0 . spawn st , and _ compare tags.focus.curframe_wcount = 0 _ spawn st , chain - split auto - cycle_frame - spawn st

hc keybind Mod1-Return spawn st
hc keybind $Mod-Shift-Return chain , shift left , focus up , shift right , focus left

hc keybind $Mod-s spawn pad rofi
hc keybind Mod1-q spawn pad sider
hc keybind Mod1-w spawn pad meme

hc keybind $Mod-b spawn tg bar
hc keybind $Mod-c spawn ctw
hc keybind $Mod-y spawn pad nerdy

hc keybind Mod1-p spawn hlc -vol i
hc keybind Mod1-Shift-p spawn hlc -vol d

hc keybind Mod1-l spawn hlc -m next
hc keybind Mod1-h spawn hlc -m prev
hc keybind Mod1-k spawn hlc -m tog
hc keybind Mod1-j spawn hlc -m tog

# layouts
hc keybind $Mod-x spawn ~/.config/herbstluftwm/layouts/centered-master

# save state
hc keybind $Mod-i spawn "hlc -ss > ~/.config/herbstluftwm/layouts/state"
hc keybind $Mod-o spawn "hlc -ls < ~/.config/herbstluftwm/layouts/state"

# focusing clients
hc keybind $Mod-h focus left #Focus left
hc keybind $Mod-j focus down #Focus down
hc keybind $Mod-k focus up #focus up
hc keybind $Mod-l focus right #Focus right

# increase/decrease frame gaps
hc keybind $Mod-g spawn hlc -fg i
hc keybind $Mod-Shift-g spawn hlc -fg d

hc keybind Mod1-g spawn hlc -wg i
hc keybind Mod1-Shift-g spawn hlc -wg d

# moving clients
hc keybind $Mod-Shift-h shift left #Move window left
hc keybind $Mod-Shift-j shift down #Move window down
hc keybind $Mod-Shift-k shift up #Move window up
hc keybind $Mod-Shift-l shift right #Move window right

hc keybind Control-Mod1-h chain , split left , focus left
hc keybind Control-Mod1-j chain , split bottom , focus down
hc keybind Control-Mod1-k chain , split top , focus up
hc keybind Control-Mod1-l chain , split right , focus right

hc keybind Control-space split explode #Explode current frame to subframes

# resizing frames
resizestep=0.02
hc keybind $Mod-Mod1-h resize left +$resizestep #Resize frame leftwards
hc keybind $Mod-Mod1-j resize down +$resizestep #Resize frames downwards
hc keybind $Mod-Mod1-k resize up +$resizestep #Resize frame upwards
hc keybind $Mod-Mod1-l resize right +$resizestep #Resize frame rightwards

tag_names=( {1..9} )
tag_keys=( {1..9} )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" spawn hlc -st f "$i"
        # hc keybind "$Mod-$key" use_index "$i" #Focus tag at number
        hc keybind "$Mod-Shift-$key" move_index "$i" #Move focus window to tag at number
        hc keybind "$Mod-Control-$key" move_and_follow "$i"
    fi
done

hc keybind $Mod-t spawn noti -d

# cycle through tags
hc keybind $Mod-d spawn hlc -st n
hc keybind $Mod-a spawn hlc -st p

hc keybind $Mod-Shift-d chain , move_index +1 --skip-visible , spawn hlc -st n
hc keybind $Mod-Shift-a chain , move_index -1 --skip-visible , spawn hlc -st p

hc keybind $Mod-space attr clients.focus.floating toggle
hc keybind $Mod-f fullscreen toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-Tab cycle_all +1
hc keybind $Mod-u jumpto urgent
hc keybind $Mod-Shift-space cycle_layout 1

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

# frame settings
hc set frame_border_active_color '#7e5d3c'
hc set frame_border_normal_color '#947e68'
hc set frame_bg_normal_color '#443a36'
hc set frame_bg_active_color '#947e68'
hc set frame_border_width 0
hc set always_show_frame false
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_gap 5
hc set snap_gap 5

# Window settings
hc set window_gap 10
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings off
hc set mouse_recenter_gap 0

hc attr theme.active.color '#201e1a'
hc attr theme.normal.color '#201e1a'
# hc attr theme.normal.color '#443a36'
# hc attr theme.active.color '#79695a'
hc attr theme.border_width 10
hc attr theme.inner_width 2
hc attr theme.floating.inner_width 2
hc attr theme.padding_top0
hc attr theme.padding_bottom 0 # 19
hc attr theme.floating.padding_left 0 #21
hc attr theme.floating.padding_bottom 0
hc attr theme.floating.border_width 9
hc attr theme.active.inner_color '#6c4848'
hc attr theme.normal.inner_color '#4f4141'
hc attr theme.floating.active.inner_color '#6c4848'
hc attr theme.floating.normal.inner_color '#4f4141'
hc attr theme.background_color '#201e1a'

hc pad 0 4 4 4 4

# rules
hc unrule -F

hc rule class=Sxiv floating=on floatplacement=center focus=on
hc rule class=mpv floating=on floatplacement=center focus=on
hc rule class=discord floating=on floatplacement=center focus=on

hc rule focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc unlock

# hc set tree_style '╾│ ├└╼─┐'
hc set tree_style "-| |'--."


hc detect_monitors

dunst &
