#!/bin/sh

# xinitrc runs automatically when you run startx.

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

setxkbmap hu & # hungarian keymap
chth -r & # pick random theme
cl & # clear home directory
sleep 1 # wait a second to properly load colors

exec awesome
