#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.
# tiramisu > ${XDG_CONFIG_HOME:-$HOME/.config}/notifs &
# dunst &
# xrdb ~/.Xresources &
# feh --bg-scale --randomize ~/.wp
# mpd &			# music player daemon-you might prefer it as a service though
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
xautolock -time 10 -locker lock &
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
# picom &		# xcompmgr for transparency
xset r rate 300 50 &	# Speed xrate up
setxkbmap hu
