map gcf cd /home/me/.config
map tcf tab_new /home/me/.config
map mcf shell mv -v %s /home/me/.config
map Ycf shell cp -rv %s /home/me/.config 
map gcfa cd /home/me/.config
map tcfa tab_new /home/me/.config
map mcfa shell mv -v %s /home/me/.config
map Ycfa shell cp -rv %s /home/me/.config 
map gD cd /home/me/etc/dl
map tD tab_new /home/me/etc/dl
map mD shell mv -v %s /home/me/etc/dl
map YD shell cp -rv %s /home/me/etc/dl 
map gd cd /home/me/etc/doc
map td tab_new /home/me/etc/doc
map md shell mv -v %s /home/me/etc/doc
map Yd shell cp -rv %s /home/me/etc/doc 
map gh cd /home/me
map th tab_new /home/me
map mh shell mv -v %s /home/me
map Yh shell cp -rv %s /home/me 
map gm cd /home/me/etc/music
map tm tab_new /home/me/etc/music
map mm shell mv -v %s /home/me/etc/music
map Ym shell cp -rv %s /home/me/etc/music 
map gpp cd /home/me/etc/pic
map tpp tab_new /home/me/etc/pic
map mpp shell mv -v %s /home/me/etc/pic
map Ypp shell cp -rv %s /home/me/etc/pic 
map gsc cd /home/me/.local/bin
map tsc tab_new /home/me/.local/bin
map msc shell mv -v %s /home/me/.local/bin
map Ysc shell cp -rv %s /home/me/.local/bin 
map gsrc cd /home/me/.local/src
map tsrc tab_new /home/me/.local/src
map msrc shell mv -v %s /home/me/.local/src
map Ysrc shell cp -rv %s /home/me/.local/src 
map gvv cd /home/me/etc/vid
map tvv tab_new /home/me/etc/vid
map mvv shell mv -v %s /home/me/etc/vid
map Yvv shell cp -rv %s /home/me/etc/vid 
map gDD cd /home/me/dev/dotfiles
map tDD tab_new /home/me/dev/dotfiles
map mDD shell mv -v %s /home/me/dev/dotfiles
map YDD shell cp -rv %s /home/me/dev/dotfiles 
map bf shell $EDITOR /home/me/.config/shell/bm-files 
map bd shell $EDITOR /home/me/.config/shell/bm-dirs 
map cfz shell $EDITOR /home/me/.config/zsh/.zshrc 
map cfu shell $EDITOR /home/me/.config/newsboat/urls 
map cfl shell $EDITOR /home/me/.config/lf/lfrc 
map ytl shell $EDITOR /home/me/.config/playlist 
map lp shell $EDITOR /home/me/.config/links 
