#!/usr/bin/env bash

# chm - choose a meme
# lists all my memes in rofi and copies the one i choose to clipboard

pic=$(echo "$(ls ~/etc/pic/meme | sed 's/.png//g')" | rofi -dmenu)

xclip -sel clip -t image/png ~/etc/pic/meme/$pic.png
