#!/bin/sh

repo=$1
repo=${repo##*/}

case $1 in
    *http*) git clone $1 ~/etc/repos/$repo ;;
    -s) git clone "git@github.com:yrwq/$2.git" ;;
    *) git clone "https://github.com/$1" ;;
esac

notify-send -a 'github' "Git" "Cloned ${repo}"
