#!/bin/sh

# cm - current music
# requires ffmpeg, metaflac, mpc, mpd, wmctrl

music_library="$HOME/etc/music"

[ "$(mpc status | grep 'playing')" ] && \
    ffmpeg -y -i "$(mpc --format \
    "$music_library"/%file% | head -n 1)" \
    /tmp/mpd_cover.jpg &&
    cover_path="/tmp/mpd_cover.jpg" && \
    notify-send -a music -i $cover_path "$(mpc current -f %artist%)" "$(mpc current -f %title%)"

[ "$(playerctl status | grep 'Playing')" ] &&
    notify-send -a music -i "$(playerctl metadata | grep 'artUrl' | awk '{print $3}')" \
    "  Currently playing" \
    "$(playerctl metadata title)"

