#! /usr/bin/env bash

# draw a terminal

read -r X Y W H < <(slop -o -f "%x %y %w %h")

(( W /= 8 ))
(( H /= 14 ))
(( X /= 1 ))
(( Y /= 1 ))

g="${W}x${H}+${X}+${Y}"

setsid -f st -c "float" -g "$g" -t "st" "${@}"
