#!/usr/bin/env python3

import os
import re
from github import Github

key = os.getenv("GITHUB_TOKEN")
# First create a Github instance:

# using an access token
g = Github(key)

events = g.get_user().get_events()

for ev in events:

    if ev.type == "WatchEvent":
        print(f"\n{ev.actor.login} \n\tstarred {ev.repo.name}")
    elif ev.type == "PushEvent":
        print(f"\n{ev.actor.login} \n\tpushed to {ev.repo.name}")
    elif ev.type == "CreateEvent":
        print(f"\n{ev.actor.login} \n\tcreated {ev.repo.name}")
    elif ev.type == "DeleteEvent":
        print(f"\n{ev.actor.login} \n\tdeleted {ev.repo.name}")
    elif ev.type == "IssuesEvent":
        print(f"\n{ev.actor.login} \n\tmade an issue to {ev.repo.name}")
    elif ev.type == "IssueCommentEvent":
        print(f"\n{ev.actor.login} \n\tcommented to an issue on {ev.repo.name}")
    elif ev.type == "PullRequestEvent":
        print(f"\n{ev.actor.login} \n\trequested a pull to {ev.repo.name}")

