#!/usr/bin/env bash

test(){
    notify-send -a test -u $1 "${1}"
}

_date(){
    notify-send -a date "$(date +'%b %d %a  %H:%M')"
}

case ${1} in
    -t)
        test "low"
        test "normal"
        test "critical"
        ;;
    -d)
        _date
        ;;
esac
