#!/bin/sh

#
# push - im so fcking lazy
#

# get current branch
branch=$(git branch | grep "*" | awk '{print $2}')

[ -z "$1" ] && \
    msg="update" || \
    msg="$1"

git add .
git commit -m "${msg}"

git push origin $branch

notify-send -a 'github' "Git" "Pushed to ${branch}"
