#!/usr/bin/env bash

t() {
    todoist "${@}"
}

_delete() {
    item="$(t list | grep "${1}" | awk '{print $1}')"
    t d "${item}"
}

case ${1} in
    d)
        _delete 
        ;;
    *)
        t ${@}
esac
