#!/bin/sh

#
# upload file to 0x0.st
#

# prevent filetypes like text/x-shellscript or text/x-diff
# autodownloading in some browsers
type=
file -ibL "$1" | grep -q '^text/' && type=';type=text/plain'

curl -sF file="@${1:--}$type" 'http://0x0.st' \
    | tee /dev/stderr \
    | xclip -r -sel clip


# curl -X POST -d "api_dev_key=$PASTEBIN_TOKEN" -d "api_paste_code=test" -d "api_option=paste" "https://pastebin.com/api/api_post.php"
