#!/usr/bin/env bash

# infinite loop youtube downloader

music_dir="$HOME/etc/music"

while :
do
    clear
    read -rp "url: " url
    cd $music_dir
    youtube-dl $url --add-metadata --embed-thumbnail --extract-audio --audio-format mp3 --restrict-filenames

done
