require("module.layout-popup")
require("module.notification")
-- require("module.titlebar.dear")
-- require("module.titlebar.xo")
require("module.titlebar.kory")
require("module.applauncher")
require("module.scratchpad")
