#!/bin/sh

urlregex="(((http|https)://|www\\.)[a-zA-Z0-9.]*[:]?[a-zA-Z0-9./@$&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)"

# First remove linebreaks and mutt sidebars:
urls="$(sed 's/.*│//g' | tr -d '\n' |
	grep -aEo "$urlregex" | # grep only urls as defined above.
	uniq | # Ignore neighboring duplicates.
	sed 's/^www./http:\/\/www\./g')"

[ -z "$urls" ] && exit

# chosen="$(echo "$urls" | dmenu -i -p 'Choose:' -l 10)"
chosen="$(echo -ne "$urls" | rofi -dmenu -i)"

if [ -z "$chosen" ]; then
	exit 1
fi

options="img\nmpv\nclip\nwget\nbrowser\nyoutube-dl"

menu="$(echo -ne $options | rofi -dmenu -i)"

case $menu in
	img)
		curl -Ss $chosen -o /tmp/temp_image.png
		sxiv /tmp/temp_image.png
		;;
	mpv)
		mpv $chosen
		;;
	wget)
		wget $chosen
		;;
	clip)
		echo "$chosen" | xclip -sel clip
		notify-send "Copied to clipboard"
		;;
	browser)
		setsid xdg-open "$chosen" >/dev/null 2>&1 &
		;;
	youtube-dl)
		youtube-dl $chosen
		;;
esac
