import = [
  "~/.config/alacritty/gruvbox.toml"
]

[font]
size = 14

[font.normal]
family = "FantasqueSansM Nerd Font"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "L"
mods = "Alt"

[window.padding]
x = 6
y = 6
